"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"


[manager]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
sort_translit = true
show_hidden = true
show_symlink = true

[preview]
image_filter = "nearest"
image_quality = 50
